/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatInterfaceRouteImport } from './routes/chat-interface'
import { Route as CallInterfaceRouteImport } from './routes/call-interface'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatInterfaceRoute = ChatInterfaceRouteImport.update({
  id: '/chat-interface',
  path: '/chat-interface',
  getParentRoute: () => rootRouteImport,
} as any)
const CallInterfaceRoute = CallInterfaceRouteImport.update({
  id: '/call-interface',
  path: '/call-interface',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call-interface': typeof CallInterfaceRoute
  '/chat-interface': typeof ChatInterfaceRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call-interface': typeof CallInterfaceRoute
  '/chat-interface': typeof ChatInterfaceRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call-interface': typeof CallInterfaceRoute
  '/chat-interface': typeof ChatInterfaceRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/call-interface' | '/chat-interface' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/call-interface' | '/chat-interface' | '/login'
  id: '__root__' | '/' | '/call-interface' | '/chat-interface' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallInterfaceRoute: typeof CallInterfaceRoute
  ChatInterfaceRoute: typeof ChatInterfaceRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-interface': {
      id: '/chat-interface'
      path: '/chat-interface'
      fullPath: '/chat-interface'
      preLoaderRoute: typeof ChatInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-interface': {
      id: '/call-interface'
      path: '/call-interface'
      fullPath: '/call-interface'
      preLoaderRoute: typeof CallInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallInterfaceRoute: CallInterfaceRoute,
  ChatInterfaceRoute: ChatInterfaceRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
