/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatInterfaceRouteImport } from './routes/chat-interface'
import { Route as IndexRouteImport } from './routes/index'

const ChatInterfaceRoute = ChatInterfaceRouteImport.update({
  id: '/chat-interface',
  path: '/chat-interface',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat-interface': typeof ChatInterfaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat-interface': typeof ChatInterfaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat-interface': typeof ChatInterfaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat-interface'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat-interface'
  id: '__root__' | '/' | '/chat-interface'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatInterfaceRoute: typeof ChatInterfaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat-interface': {
      id: '/chat-interface'
      path: '/chat-interface'
      fullPath: '/chat-interface'
      preLoaderRoute: typeof ChatInterfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatInterfaceRoute: ChatInterfaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
